"""
Base Trainer Module

Provides an abstract base class for all model trainers in the ALPR system.
This ensures consistent interface and data path handling across different
model architectures (YOLOv11, YOLOv26, etc.).

Author: ALPR Thesis Project
"""

import os
import yaml
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, Set

class BaseTrainer(ABC):
    """
    Abstract base class for all model trainers.
    
    This class establishes a common interface for training different object detection
    models and handles standardized data path resolution.
    
    Attributes:
        cfg (dict): Master configuration dictionary loaded from YAML
        data_root (str): Absolute path to processed data directory
        yolo_yaml (str): Path to YOLO-format data configuration file
        (COCO JSON annotations are not used in this project.)
    
    Note:
        All derived classes must implement the train() method.
    """
    
    def __init__(self, cfg):
        """
        Initialize base trainer with configuration.
        
        Args:
            cfg (dict): Master configuration dictionary containing:
                - data_engine: Data processing settings
                - models: Model-specific hyperparameters
                - output_dir: Training output directory
        """
        self.cfg = cfg
        
        # Resolve absolute path to processed data root directory
        self.data_root = os.path.abspath(cfg['data_engine']['target_path'])
        
        # Path to YOLO-format configuration file (generated by converter.py)
        self.yolo_yaml = os.path.join("configs", "final_data.yaml")
        
        # Note: this project no longer generates COCO JSON annotations.

    def _ultralytics_valid_cfg_keys(self) -> Optional[Set[str]]:
        """
        Best-effort discovery of valid Ultralytics train() configuration keys.

        Ultralytics validates kwargs against its default config; passing unknown keys
        can raise runtime errors. We try to load the default config keys and filter
        any computed kwargs accordingly.
        """
        try:
            from ultralytics.cfg import DEFAULT_CFG_DICT  # type: ignore

            if isinstance(DEFAULT_CFG_DICT, dict):
                return set(DEFAULT_CFG_DICT.keys())
        except Exception:
            pass

        try:
            import pkgutil

            data = pkgutil.get_data("ultralytics", "cfg/default.yaml")
            if not data:
                return None
            defaults = yaml.safe_load(data.decode("utf-8"))
            if isinstance(defaults, dict):
                return set(defaults.keys())
        except Exception:
            return None

        return None

    def _filter_ultralytics_kwargs(self, kwargs: Dict[str, Any]) -> Dict[str, Any]:
        valid = self._ultralytics_valid_cfg_keys()
        if not valid:
            return kwargs
        return {k: v for k, v in kwargs.items() if k in valid}

    def ultralytics_augmentation_kwargs(self) -> Dict[str, Any]:
        """
        Map this project's augmentation config onto Ultralytics training kwargs.

        This replaces the previous Albumentations *offline* augmentation.
        """
        aug_cfg = (self.cfg.get("data_engine") or {}).get("augmentation") or {}
        params = aug_cfg.get("params") or {}
        enable = bool(aug_cfg.get("enable", True))

        # A small, conservative set of Ultralytics augmentations that roughly matches
        # the previous Albumentations pipeline (color jitter + mild affine).
        if not enable:
            aug = {
                "hsv_h": 0.0,
                "hsv_s": 0.0,
                "hsv_v": 0.0,
                "degrees": 0.0,
                "translate": 0.0,
                "scale": 0.0,
                "shear": 0.0,
                "perspective": 0.0,
                "flipud": 0.0,
                "fliplr": 0.0,
                "mosaic": 0.0,
                "mixup": 0.0,
                "copy_paste": 0.0,
            }
            return self._filter_ultralytics_kwargs(aug)

        use_affine = bool(params.get("shift_scale_rotate", True))
        use_bc = bool(params.get("brightness_contrast"))

        aug = {
            # Previous pipeline used small brightness/contrast changes; HSV is the closest match.
            "hsv_h": 0.0,
            "hsv_s": 0.2 if use_bc else 0.0,
            "hsv_v": 0.2 if use_bc else 0.0,
            # Mild geometric transforms similar to ShiftScaleRotate/Affine.
            "degrees": 10.0 if use_affine else 0.0,
            "translate": 0.0625 if use_affine else 0.0,
            "scale": 0.10 if use_affine else 0.0,
            "shear": 5.0 if params.get("shear") else 0.0,
            "perspective": 0.001 if params.get("perspective") else 0.0,
            # Avoid introducing strong new augmentations not used previously.
            "mosaic": 0.0,
            "mixup": 0.0,
            "copy_paste": 0.0,
        }

        return self._filter_ultralytics_kwargs(aug)

    def ultralytics_optimizer_lr_kwargs(self, model_cfg: Dict[str, Any]) -> Dict[str, Any]:
        """
        Extract optimizer/learning-rate options from a model's config block and
        convert them into Ultralytics training kwargs.

        Supported keys in `model_cfg`:
            - optimizer: "auto" (default), "sgd", "adam", "adamw", ...
            - lr0: base learning rate (float)
            - lr: alias for lr0 (float)
            - amp: enable Automatic Mixed Precision (bool)
            - cache: cache images for faster training (bool or str, Ultralytics-dependent)
        """
        if not isinstance(model_cfg, dict):
            return {}

        kwargs: Dict[str, Any] = {}

        optimizer = model_cfg.get("optimizer", "auto")
        if optimizer is not None:
            kwargs["optimizer"] = optimizer

        # Ultralytics uses `lr0` as the base LR. We also accept `lr` as a friendlier alias.
        lr0 = model_cfg.get("lr0", model_cfg.get("lr", None))
        if lr0 is not None:
            kwargs["lr0"] = float(lr0)

        amp = model_cfg.get("amp", None)
        if amp is not None:
            kwargs["amp"] = bool(amp)

        cache = model_cfg.get("cache", None)
        if cache is not None:
            kwargs["cache"] = cache

        return self._filter_ultralytics_kwargs(kwargs)

    @abstractmethod
    def train(self):
        """
        Execute the training loop.
        
        This method must be implemented by all subclasses to define
        model-specific training procedures.
        
        Raises:
            NotImplementedError: If subclass does not implement this method
        """
        pass