"""
Base Trainer Module

Provides an abstract base class for all model trainers in the ALPR system.
This ensures consistent interface and data path handling across different
model architectures (YOLOv11, YOLOv10, RT-DETRv2, etc.).

Author: ALPR Thesis Project
"""

import os
import yaml
from abc import ABC, abstractmethod

class BaseTrainer(ABC):
    """
    Abstract base class for all model trainers.
    
    This class establishes a common interface for training different object detection
    models and handles standardized data path resolution.
    
    Attributes:
        cfg (dict): Master configuration dictionary loaded from YAML
        data_root (str): Absolute path to processed data directory
        yolo_yaml (str): Path to YOLO-format data configuration file
        train_json (str): Path to COCO-format training annotations
        val_json (str): Path to COCO-format validation annotations
        test_json (str): Path to COCO-format test annotations
    
    Note:
        All derived classes must implement the train() method.
    """
    
    def __init__(self, cfg):
        """
        Initialize base trainer with configuration.
        
        Args:
            cfg (dict): Master configuration dictionary containing:
                - data_engine: Data processing settings
                - models: Model-specific hyperparameters
                - output_dir: Training output directory
        """
        self.cfg = cfg
        
        # Resolve absolute path to processed data root directory
        self.data_root = os.path.abspath(cfg['data_engine']['target_path'])
        
        # Path to YOLO-format configuration file (generated by converter.py)
        self.yolo_yaml = os.path.join("configs", "final_data.yaml")
        
        # COCO JSON annotation paths (standardized locations from converter.py)
        self.train_json = os.path.join(self.data_root, "annotations", "instances_train.json")
        self.val_json = os.path.join(self.data_root, "annotations", "instances_val.json")
        self.test_json = os.path.join(self.data_root, "annotations", "instances_test.json")

    @abstractmethod
    def train(self):
        """
        Execute the training loop.
        
        This method must be implemented by all subclasses to define
        model-specific training procedures.
        
        Raises:
            NotImplementedError: If subclass does not implement this method
        """
        pass