"""
RT-DETRv2 Trainer Module

Implements RT-DETRv2 training using the Ultralytics framework.
RT-DETR (Real-Time Detection Transformer) is a transformer-based object detector
that achieves high accuracy while maintaining competitive inference speed.

Key Features:
    - End-to-end transformer architecture
    - No NMS post-processing required
    - Unified Ultralytics interface (consistent with YOLOv11 and YOLOv10)

Author: ALPR Thesis Project
"""

import os
from ultralytics import RTDETR
from .base_trainer import BaseTrainer

class RTDETRv2Trainer(BaseTrainer):
    """
    RT-DETRv2 model trainer using Ultralytics framework.
    
    This trainer handles RT-DETRv2-specific model initialization and training
    using the standardized YOLO-format dataset configuration.
    
    Supported RT-DETR variants:
        - rtdetr-l.pt (large)
        - rtdetr-x.pt (extra-large)
    """
    
    def train(self):
        """
        Execute RT-DETRv2 training pipeline.
        
        Loads the specified RT-DETR variant and trains it on the processed
        dataset using hyperparameters from the configuration file.
        
        Training outputs:
            - Trained weights: {output_dir}/rtdetrv2_run/weights/best.pt
            - Training metrics: {output_dir}/rtdetrv2_run/results.csv
            - Validation results: {output_dir}/rtdetrv2_run/val/
        
        Configuration keys used:
            - models.rtdetrv2.model_name: Pre-trained model variant (e.g., 'rtdetr-l.pt')
            - models.rtdetrv2.epochs: Number of training epochs
            - models.rtdetrv2.batch: Batch size for training
            - data_engine.img_size: Input image size (square)
            - output_dir: Base directory for training outputs
        """
        print("--- Starting RT-DETRv2 Training (Ultralytics) ---")
        
        # Load pre-trained RT-DETR model
        model_name = self.cfg['models']['rtdetrv2']['model_name']  # e.g., 'rtdetr-l.pt'
        model = RTDETR(model_name)
        
        # Configure training output directory
        save_dir = os.path.join(self.cfg['output_dir'], 'rtdetrv2_run')
        
        # Execute training with Ultralytics trainer
        # Uses YOLO-format data configuration generated by converter.py
        results = model.train(
            data=self.yolo_yaml,                                    # Path to data YAML
            epochs=self.cfg['models']['rtdetrv2']['epochs'],        # Training epochs
            batch=self.cfg['models']['rtdetrv2']['batch'],          # Batch size
            imgsz=self.cfg['data_engine']['img_size'],              # Input image size
            save_dir=save_dir,                                       # Output directory
            workers=4,                                               # DataLoader workers
            exist_ok=True,                                           # Overwrite existing runs
            device=0                                                 # GPU device (0=first GPU, 'cpu' for CPU, [0,1,2,3] for multi-GPU)
        )
        
        print(f"RT-DETRv2 Training Finished. Weights saved at: {save_dir}/weights/best.pt")
