"""
RT-DETRv2 Trainer Module

Implements RT-DETRv2 training using the official PyTorch implementation.
RT-DETR (Real-Time Detection Transformer) is a transformer-based object detector
that achieves high accuracy while maintaining competitive inference speed.

Key Features:
    - End-to-end transformer architecture
    - No NMS post-processing required
    - COCO-format data input
    - Support for various backbone architectures (ResNet, ResNeXt, etc.)

Author: ALPR Thesis Project
"""

import os
import sys
import yaml
from .base_trainer import BaseTrainer

class RTDETRv2Trainer(BaseTrainer):
    """
    RT-DETRv2 model trainer using official PyTorch implementation.
    
    This trainer handles RT-DETRv2-specific model initialization and training
    using COCO-format annotations generated by the data converter.
    
    Supported Backbones:
        - ResNet-18/34/50/101
        - ResNeXt-50/101
        - Vision Transformers
    
    Note:
        RT-DETR requires the official implementation repository in models/rtdetr_pytorch/
        Clone from: https://github.com/lyuwenyu/RT-DETR
    """
    
    def train(self):
        """
        Execute RT-DETRv2 training pipeline.
        
        Loads the RT-DETRv2 model from config and trains it on the processed
        dataset using COCO-format annotations.
        
        Training outputs:
            - Trained weights: {output_dir}/rtdetrv2_run/checkpoint_best.pth
            - Training metrics: {output_dir}/rtdetrv2_run/logs/
            - Validation results: {output_dir}/rtdetrv2_run/eval/
        
        Configuration keys used:
            - models.rtdetrv2.config_file: Path to RT-DETR model config YAML
            - models.rtdetrv2.epochs: Number of training epochs
            - models.rtdetrv2.batch: Batch size for training
            - data_engine.img_size: Input image size
            - output_dir: Base directory for training outputs
        
        Raises:
            ImportError: If RT-DETR implementation is not found
            FileNotFoundError: If config file or data annotations don't exist
        """
        print("--- Starting RT-DETRv2 Training ---")
        
        # Add RT-DETR implementation to Python path
        rtdetr_path = os.path.join(os.getcwd(), 'models', 'rtdetr_pytorch')
        if rtdetr_path not in sys.path:
            sys.path.insert(0, rtdetr_path)
        
        try:
            from src.core import YAMLConfig
            from src.solver import TASKS
        except ImportError as e:
            raise ImportError(
                f"RT-DETR implementation not found: {e}\n"
                "Please clone the repository:\n"
                "  cd models/\n"
                "  git clone https://github.com/lyuwenyu/RT-DETR.git rtdetr_pytorch\n"
                "Or download from: https://github.com/lyuwenyu/RT-DETR"
            )
        
        # Get RT-DETR configuration file path
        rtdetr_config_file = self.cfg['models']['rtdetrv2']['config_file']
        
        if not os.path.exists(rtdetr_config_file):
            raise FileNotFoundError(
                f"RT-DETR config file not found: {rtdetr_config_file}\n"
                f"Please ensure the config file exists at the specified path."
            )
        
        # Configure output directory BEFORE loading RT-DETR config
        save_dir = os.path.join(self.cfg['output_dir'], 'rtdetrv2_run')
        os.makedirs(save_dir, exist_ok=True)
        
        # Load RT-DETR configuration
        print(f"Loading RT-DETR config from: {rtdetr_config_file}")
        rtdetr_cfg = YAMLConfig(
            rtdetr_config_file,
            resume=None,
            use_amp=True,  # Use automatic mixed precision for faster training
            tuning=''
        )
        
        # Immediately override output_dir after loading config
        # Need to set both the yaml_cfg dict AND the direct attribute
        rtdetr_cfg.yaml_cfg['output_dir'] = save_dir
        rtdetr_cfg.output_dir = save_dir  # This is what RT-DETR actually uses
        
        # Override data paths with our processed COCO annotations
        print("Configuring data paths...")
        
        # Update train dataset path
        rtdetr_cfg.yaml_cfg['train_dataloader']['dataset']['img_folder'] = os.path.join(
            self.data_root, 'images/train'
        )
        rtdetr_cfg.yaml_cfg['train_dataloader']['dataset']['ann_file'] = self.train_json
        
        # Update validation dataset path
        rtdetr_cfg.yaml_cfg['val_dataloader']['dataset']['img_folder'] = os.path.join(
            self.data_root, 'images/val'
        )
        rtdetr_cfg.yaml_cfg['val_dataloader']['dataset']['ann_file'] = self.val_json
        
        # Update number of classes based on our config
        # Note: We do NOT override epochs or batch size - using author's carefully tuned defaults
        num_classes = len(self.cfg['classes'])
        rtdetr_cfg.yaml_cfg['num_classes'] = num_classes
        
        print(f"Training configuration:")
        print(f"  - Using RT-DETR's default hyperparameters (epochs, batch size, LR schedule)")
        print(f"  - Number of classes: {num_classes}")
        print(f"  - Train annotations: {self.train_json}")
        print(f"  - Val annotations: {self.val_json}")
        print(f"  - Output directory: {save_dir}")
        print(f"\n  To modify RT-DETR hyperparameters, edit: {rtdetr_config_file}")
        
        # Verify annotation files exist
        if not os.path.exists(self.train_json):
            raise FileNotFoundError(
                f"Training annotations not found: {self.train_json}\n"
                f"Please run: python data_engine/converter.py"
            )
        
        if not os.path.exists(self.val_json):
            raise FileNotFoundError(
                f"Validation annotations not found: {self.val_json}\n"
                f"Please run: python data_engine/converter.py"
            )
        
        # Initialize solver (trainer)
        print("\nInitializing RT-DETR solver...")
        solver = TASKS[rtdetr_cfg.yaml_cfg['task']](rtdetr_cfg)
        
        # Start training
        print("\nStarting training loop...")
        print("="*70)
        solver.fit()
        print("="*70)
        
        print(f"\nRT-DETRv2 Training Finished!")
        print(f"Best weights saved at: {save_dir}/checkpoint_best.pth")
        print(f"Training logs: {save_dir}/logs/")
        
        # Print evaluation results if available
        eval_results_path = os.path.join(save_dir, 'eval_results.json')
        if os.path.exists(eval_results_path):
            print(f"Evaluation results: {eval_results_path}")
