"""
YOLOv11 Trainer Module

Implements YOLOv11 training using the Ultralytics framework.
YOLOv11 is the latest iteration of the YOLO series, offering improved
accuracy and speed for object detection tasks.

Author: ALPR Thesis Project
"""

import os
from ultralytics import YOLO
from .base_trainer import BaseTrainer

class YOLOv11Trainer(BaseTrainer):
    """
    YOLOv11 model trainer using Ultralytics framework.
    
    This trainer handles YOLOv11-specific model initialization and training
    using the standardized YOLO-format dataset configuration.
    
    Supported YOLOv11 variants:
        - yolo11n.pt (nano)
        - yolo11s.pt (small)
        - yolo11m.pt (medium)
        - yolo11l.pt (large)
        - yolo11x.pt (extra-large)
    """
    
    def train(self):
        """
        Execute YOLOv11 training pipeline.
        
        Loads the specified YOLOv11 variant and trains it on the processed
        dataset using hyperparameters from the configuration file.
        
        Training outputs:
            - Trained weights: {output_dir}/yolov11_run/weights/best.pt
            - Training metrics: {output_dir}/yolov11_run/results.csv
            - Validation results: {output_dir}/yolov11_run/val/
        
        Configuration keys used:
            - models.yolov11.model_name: Pre-trained model variant (e.g., 'yolo11s.pt')
            - models.yolov11.epochs: Number of training epochs
            - models.yolov11.batch: Batch size for training
            - data_engine.img_size: Input image size (square)
            - output_dir: Base directory for training outputs
        """
        print("--- Starting YOLOv11 Training ---")
        
        # Load pre-trained YOLOv11 model
        model_name = self.cfg['models']['yolov11']['model_name']  # e.g., 'yolo11s.pt'
        model = YOLO(model_name)
        
        # Configure training output directory
        save_dir = os.path.join(self.cfg['output_dir'], 'yolov11_run')
        
        # Execute training with Ultralytics trainer
        # Uses YOLO-format data configuration generated by converter.py
        results = model.train(
            data=self.yolo_yaml,                                    # Path to data YAML
            epochs=self.cfg['models']['yolov11']['epochs'],         # Training epochs
            batch=self.cfg['models']['yolov11']['batch'],           # Batch size
            imgsz=self.cfg['data_engine']['img_size'],              # Input image size
            save_dir=save_dir,                                      # Output directory
            workers=4,                                              # DataLoader workers
            exist_ok=True,                                          # Overwrite existing runs
            device=0,                                               # GPU device (0=first GPU, 'cpu' for CPU, [0,1,2,3] for multi-GPU)
            patience=self.cfg['models']['yolov11']['patience'],     # Early stopping patience
        )
        
        print(f"YOLOv11 Training Finished. Weights saved at: {save_dir}/weights/best.pt")
